# Generated by Django 3.2.4 on 2022-01-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_input',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user_input',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='user_input',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_input',
            name='phone',
        ),
    ]
