# Generated by Django 3.2.4 on 2022-01-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220112_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_action',
            name='score',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
