# Generated by Django 3.2.4 on 2022-01-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_action_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, default=0, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_action',
            name='score',
        ),
    ]
