# Generated by Django 3.2.4 on 2022-01-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220112_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='bot_score',
        ),
        migrations.AddField(
            model_name='score',
            name='user_score',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
