# Generated by Django 3.2.4 on 2022-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220112_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='tie',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
